### ISSUE TITLE
Mixed content error for tile.stamen.js

### ISSUE THREAD

**Issue by rbreslow** [raster-foundry/map-warpr#1]
https://github.com/raster-foundry/map-warpr/blob/c44f27a29436f024aca2626b6ed5d49940c13ccf/index.html#L134

```
Mixed Content: The page at 'https://warpr.io/' was loaded over HTTPS, but requested an insecure script 'http://maps.stamen.com/js/tile.stamen.js?v1.3.0'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by hectcastro** [comment]
It doesn't seem like this asset can be served by `maps.stamen.com` with a valid TLS certificate (I even tried the Fastly specific domain that usually works for tiles).

Given that, we should download the contents of this file and include it in the project (like the other local JavaScript files). We should do this as part of https://github.com/azavea/raster-foundry-platform/issues/319.
